# Семинар 1. Numpy

Сегодня познакомимся с библиотекой Numpy

In [2]:
print(1)
print(10)
print(12000)

1
10
12000


In [16]:
1
10
12000

12000

In [3]:
x = 9

In [4]:
print(x)

9


In [5]:
print(100000)

100000


### Numpy

In [6]:
import numpy as np

#### Создание массивов

In [12]:
data = np.array([[10, 3, 13], [17, 8, 0], [15, 7, 3], [2, 19, 1], [20, 0, 0]])

In [13]:
data

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3],
       [ 2, 19,  1],
       [20,  0,  0]])

In [9]:
data.shape

(5, 3)

In [10]:
data = np.array([10, 3, 13])
data

array([10,  3, 13])

In [11]:
data.shape

(3,)

In [23]:
a = np.ones((3, 2), dtype=bool)
a

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [25]:
a = np.ones((3, 2), dtype=float)
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
a = np.ones((3, 2), dtype=int)
a

array([[1, 1],
       [1, 1],
       [1, 1]])

In [15]:
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.zeros(shape=(2, 3), dtype=bool)

array([[False, False, False],
       [False, False, False]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.random.rand(3, 4)

array([[0.02698283, 0.17991708, 0.09920731, 0.9293955 ],
       [0.34773052, 0.37705727, 0.41010174, 0.0418209 ],
       [0.26999025, 0.12747743, 0.02640891, 0.24108763]])

In [28]:
x = np.arange(10)

In [29]:
x.shape

(10,)

In [32]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
x.reshape(3, 3) # ошибка

ValueError: cannot reshape array of size 10 into shape (3,3)

### Операции с массивами

* поэлементные
* матричные
* агрегирующие

Поэлементные операции

In [35]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
x / 11

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182])

In [37]:
x * x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [41]:
a = np.random.randint(5, size=10)
a

array([1, 0, 1, 2, 4, 0, 4, 1, 3, 2])

In [42]:
a * x

array([ 0,  0,  2,  6, 16,  0, 24,  7, 24, 18])

In [43]:
data ** 2

array([[100,   9, 169],
       [289,  64,   0],
       [225,  49,   9],
       [  4, 361,   1],
       [400,   0,   0]])

In [45]:
np.sin(data)

array([[-0.54402111,  0.14112001,  0.42016704],
       [-0.96139749,  0.98935825,  0.        ],
       [ 0.65028784,  0.6569866 ,  0.14112001],
       [ 0.90929743,  0.14987721,  0.84147098],
       [ 0.91294525,  0.        ,  0.        ]])

In [46]:
x * data # ошибка

ValueError: operands could not be broadcast together with shapes (10,) (5,3) 

Матричные операции

In [47]:
y = np.random.rand(3, 2)
y

array([[0.54086824, 0.99783317],
       [0.05862408, 0.29242034],
       [0.33667358, 0.12179014]])

In [48]:
np.dot(data, y)
# data: (5, 3)
# y: (3, 2)
# result: (5, 2)

array([[ 9.96131118, 12.43886455],
       [ 9.66375264, 19.30252664],
       [ 9.53341284, 17.37981038],
       [ 2.53226758,  7.673443  ],
       [10.81736471, 19.95666341]])

In [49]:
data.dot(y)

array([[ 9.96131118, 12.43886455],
       [ 9.66375264, 19.30252664],
       [ 9.53341284, 17.37981038],
       [ 2.53226758,  7.673443  ],
       [10.81736471, 19.95666341]])

In [50]:
data @ y

array([[ 9.96131118, 12.43886455],
       [ 9.66375264, 19.30252664],
       [ 9.53341284, 17.37981038],
       [ 2.53226758,  7.673443  ],
       [10.81736471, 19.95666341]])

In [53]:
q = np.eye(5)
print(q)
np.linalg.inv(q)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Агрегирующие операции

In [54]:
np.sum(data)

118

In [55]:
np.mean(data)

7.866666666666666

In [56]:
np.max(data)

20

In [57]:
data

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3],
       [ 2, 19,  1],
       [20,  0,  0]])

In [58]:
np.sum(data, axis=1)

array([26, 25, 25, 22, 20])

In [59]:
np.sum(data, axis=0)

array([64, 37, 17])

In [60]:
np.max(data, axis=1)

array([13, 17, 15, 19, 20])

### Объединение массивов

In [61]:
data2 = np.array([[18, 2, 0], [7, 11, 0]])

In [62]:
np.vstack((data, data2))

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3],
       [ 2, 19,  1],
       [20,  0,  0],
       [18,  2,  0],
       [ 7, 11,  0]])

In [64]:
np.hstack((data, data))

array([[10,  3, 13, 10,  3, 13],
       [17,  8,  0, 17,  8,  0],
       [15,  7,  3, 15,  7,  3],
       [ 2, 19,  1,  2, 19,  1],
       [20,  0,  0, 20,  0,  0]])

In [69]:
np.concatenate((data, data2), axis=0)

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3],
       [ 2, 19,  1],
       [20,  0,  0],
       [18,  2,  0],
       [ 7, 11,  0]])

### Задача

Присоединить в data четвертый столбец - сумму по строкам

In [70]:
import numpy as np

In [71]:
sums = np.sum(data, axis=1)
sums

array([26, 25, 25, 22, 20])

In [73]:
data.shape

(5, 3)

In [75]:
sums.shape

(5,)

In [79]:
sums2 = sums.reshape(5, 1)
sums2.shape

(5, 1)

In [80]:
np.hstack((data, sums2))

array([[10,  3, 13, 26],
       [17,  8,  0, 25],
       [15,  7,  3, 25],
       [ 2, 19,  1, 22],
       [20,  0,  0, 20]])

In [81]:
sums = np.sum(data, axis=1)
sums2 = sums.reshape(5, 1)
np.hstack((data, sums2))

array([[10,  3, 13, 26],
       [17,  8,  0, 25],
       [15,  7,  3, 25],
       [ 2, 19,  1, 22],
       [20,  0,  0, 20]])

In [83]:
sums = data.sum(axis=1)
sums2 = sums.reshape(5, 1)
np.concatenate((data, sums2), axis=1)

array([[10,  3, 13, 26],
       [17,  8,  0, 25],
       [15,  7,  3, 25],
       [ 2, 19,  1, 22],
       [20,  0,  0, 20]])

In [84]:
sums = np.sum(data, axis=0)
sums2 = sums.reshape(1, 3)
np.vstack((data, sums2))

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3],
       [ 2, 19,  1],
       [20,  0,  0],
       [64, 37, 17]])

In [87]:
sums = data.sum(axis=1)
sums2 = sums.reshape(data.shape[0], 1)
np.concatenate((data, sums2), axis=1)

array([[10,  3, 13, 26],
       [17,  8,  0, 25],
       [15,  7,  3, 25],
       [ 2, 19,  1, 22],
       [20,  0,  0, 20]])

In [86]:
data.shape[0]

5

In [88]:
sums = data.sum(axis=1)
sums2 = sums.reshape(-1, 1)
np.concatenate((data, sums2), axis=1)

array([[10,  3, 13, 26],
       [17,  8,  0, 25],
       [15,  7,  3, 25],
       [ 2, 19,  1, 22],
       [20,  0,  0, 20]])

In [93]:
x.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Индексация

In [94]:
data

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3],
       [ 2, 19,  1],
       [20,  0,  0]])

In [98]:
data[3, :]

array([ 2, 19,  1])

In [96]:
data[0]

array([10,  3, 13])

In [97]:
data[:, 1]

array([ 3,  8,  7, 19,  0])

In [99]:
data[:, 0]

array([10, 17, 15,  2, 20])

In [100]:
data

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3],
       [ 2, 19,  1],
       [20,  0,  0]])

In [101]:
data[:3, 1]

array([3, 8, 7])

In [102]:
data[:3]

array([[10,  3, 13],
       [17,  8,  0],
       [15,  7,  3]])

### Задача
Выделить первые два столбца

In [103]:
data[:, :2]

array([[10,  3],
       [17,  8],
       [15,  7],
       [ 2, 19],
       [20,  0]])

In [104]:
data[:, ::2]

array([[10, 13],
       [17,  0],
       [15,  3],
       [ 2,  1],
       [20,  0]])

In [105]:
data[::2]

array([[10,  3, 13],
       [15,  7,  3],
       [20,  0,  0]])