# Классы в питоне

In [ ]:
# функция
def count(x):
    return x+1

In [15]:
import numpy as np

In [16]:
class MeanComputer:
    def __init__(self, use_mean=True):
        print("I'm initing")
        self.numbers = []
        self.use_mean = use_mean
    
    def add_number(self, number):
        self.numbers.append(number)
    
    def print_mean(self):
        if self.use_mean:
            mean = sum(self.numbers) / len(self.numbers)
            print("Mean = ", mean)
        else:
            median = np.median(self.numbers)
            print("Median = ", median)

класс Fruits:
    функция add_fruit: добавляет новую строчку в список фруктов
    функция print_fruits: печатает "У меня есть фрукты: " и через запятую перечисляет все фрукты
    
Более сложная версия: функция print_fruits: печатает "I have fruits: " и через запятую перечисляет _сколько каких фруктов_, например 2 apples, 1 banana
И чтобы в init было переключение между двумя режимами!
    

In [27]:
fruits = ["apple", "orange", "banana"]
",,, ".join(fruits)

'apple,,, orange,,, banana'

In [24]:
computer = MeanComputer(use_mean=True)
computer.add_number(10)
computer.add_number(15)
computer.add_number(200)
computer.print_mean()

I'm initing
Mean =  75.0


In [25]:
computer = MeanComputer(use_mean=False)
computer.add_number(10)
computer.add_number(15)
computer.add_number(200)
computer.print_mean()

I'm initing
Median =  15.0


In [22]:
print(computer.numbers)
print(computer.use_mean)

[10, 15, 200]
False


In [23]:
# такого атрибута нет
computer.median

AttributeError: 'MeanComputer' object has no attribute 'median'

In [36]:
class Fruits:
    def __init__(self):
        self.fruits = []
        
    def add_fruit(self, fruit):
        self.fruits.append(fruit)
        
    def print_fruits(self):
        #print(self.fruits)
        #print(", ".join(self.fruits))
        print("I have fruits: "+", ".join(self.fruits))

In [38]:
fruits = Fruits()
fruits.add_fruit("apple")
fruits.add_fruit("orange")
fruits.add_fruit("banana")
fruits.add_fruit("apple")
fruits.add_fruit("watermellon")
fruits.add_fruit("watermellon")
fruits.add_fruit("watermellon")
fruits.print_fruits()

I have fruits: apple, orange, banana, apple, watermellon, watermellon, watermellon


In [47]:
class Fruits:
    def __init__(self, use_repeats=False):
        self.use_repeats = use_repeats
        if not self.use_repeats:
            self.fruits = []
        else:
            self.fruits = {}
        
    def add_fruit(self, fruit):
        if not self.use_repeats:
            self.fruits.append(fruit)
        else:
            if not fruit in self.fruits:
                self.fruits[fruit] = 1
            else:
                self.fruits[fruit] += 1
        
    def print_fruits(self):
        if not self.use_repeats:
            #print(self.fruits)
            #print(", ".join(self.fruits))
            print("I have fruits: "+", ".join(self.fruits))
        else:
            pairs = [str(count)+" "+fruit  for fruit, count in self.fruits.items()]
            print("I have fruits: "+", ".join(pairs))

In [46]:
fruits = {"orange":2, "banana":1}
pairs = [str(count)+" "+fruit  for fruit, count in fruits.items()]
print(pairs)
", ".join(pairs)

['2 orange', '1 banana']


'2 orange, 1 banana'

In [43]:
fruits.items()

dict_items([('orange', 2), ('banana', 1)])

In [49]:
fruits = Fruits(use_repeats=True)
fruits.add_fruit("apple")
fruits.add_fruit("orange")
fruits.add_fruit("banana")
fruits.add_fruit("apple")
fruits.add_fruit("watermellon")
fruits.add_fruit("watermellon")
fruits.add_fruit("watermellon")
fruits.print_fruits()

I have fruits: 2 apple, 1 orange, 1 banana, 3 watermellon


### Sklearn

In [ ]:
class LinearRegression:
    def __init__(self, ):
        pass
    
    def fit(self, X, y):
    # обучение
        self.weights = .... # параметры
    
    def predict(self, X):
    # предсказание
        y_pred = .... self.weights.....

### Загрузим данные и обучим модель с помощью sklearn

In [50]:
import pandas as pd

In [51]:
data = pd.read_excel("https://github.com/nadiinchi/intro_sklearn/blob/master/boston_houses.xlsx?raw=true")

/Users/nadiinchi/opt/anaconda3/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)


In [52]:
data.head()

crim_rate    zn  business  river  nit_oxiden     rooms       age      dist  \
0   0.000000  0.18  0.067815      0    0.314815  0.577505  0.641607  0.269203   
1   0.000236  0.00  0.242302      0    0.172840  0.547998  0.782698  0.348962   
2   0.000236  0.00  0.242302      0    0.172840  0.694386  0.599382  0.348962   
3   0.000293  0.00  0.063050      0    0.150206  0.658555  0.441813  0.448545   
4   0.000705  0.00  0.063050      0    0.150206  0.687105  0.528321  0.448545   

   highways_index       tax  pup_per_teaс     lower  target  
0        0.000000  0.208015      0.287234  0.089680    24.0  
1        0.043478  0.104962      0.553191  0.204470    21.6  
2        0.043478  0.104962      0.553191  0.063466    34.7  
3        0.086957  0.066794      0.648936  0.033389    33.4  
4        0.086957  0.066794      0.648936  0.099338    36.2

#### Небольшая подготовка данных

In [54]:
X = data[data.columns[:-1]]
y = data["target"]

In [55]:
X.head()

crim_rate    zn  business  river  nit_oxiden     rooms       age      dist  \
0   0.000000  0.18  0.067815      0    0.314815  0.577505  0.641607  0.269203   
1   0.000236  0.00  0.242302      0    0.172840  0.547998  0.782698  0.348962   
2   0.000236  0.00  0.242302      0    0.172840  0.694386  0.599382  0.348962   
3   0.000293  0.00  0.063050      0    0.150206  0.658555  0.441813  0.448545   
4   0.000705  0.00  0.063050      0    0.150206  0.687105  0.528321  0.448545   

   highways_index       tax  pup_per_teaс     lower  
0        0.000000  0.208015      0.287234  0.089680  
1        0.043478  0.104962      0.553191  0.204470  
2        0.043478  0.104962      0.553191  0.063466  
3        0.086957  0.066794      0.648936  0.033389  
4        0.086957  0.066794      0.648936  0.099338

In [56]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: target, dtype: float64

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.3)

In [60]:
X_tr.shape

(354, 12)

In [61]:
X_te.shape

(152, 12)

#### Обучение модели

In [62]:
from sklearn.linear_model import LinearRegression

In [66]:
model = LinearRegression()
model.fit(X_tr, y_tr)

LinearRegression()

In [67]:
model.coef_ # тут хранятся параметры

array([-10.36522468,   5.66486556,  -0.82676784,   3.8016534 ,
        -8.75383967,  18.51235222,  -0.38773334, -17.45733344,
         5.60470817,  -6.09813121,  -7.98080278, -17.44787074])

#### Предсказание

In [68]:
preds_tr = model.predict(X_tr)
preds_te = model.predict(X_te)

In [71]:
preds_te[:10]

array([19.49351706, 22.69746652, 31.93550633, 17.62007815, 17.42656531,
        7.43479707, 14.47970801, 23.96957512, 18.65632618, 27.72988208])

In [76]:
y_te[:10].values

array([20.4, 19.8, 33.2, 20.2, 18.4,  8.4, 19.7, 23.1, 18.2, 24.5])

In [80]:
y_te.mean()

22.784868421052636

#### Измерение качества модели

In [77]:
from sklearn.metrics import mean_absolute_error # средняя ошибка

In [78]:
mean_absolute_error(y_tr, preds_tr)

3.4060353558761776

In [79]:
mean_absolute_error(y_te, preds_te)

3.216743173379625

In [81]:
from sklearn.neighbors import KNeighborsRegressor

In [82]:
model = KNeighborsRegressor()
model.fit(X_tr, y_tr)
preds_tr = model.predict(X_tr)
preds_te = model.predict(X_te)
print("Train:", mean_absolute_error(y_tr, preds_tr))
print("Test:", mean_absolute_error(y_te, preds_te))

Train: 2.545310734463277
Test: 3.4919736842105262
